[project]
name = "grocy-mcp-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.22.0",
    "uvicorn[standard]>=0.38.0",
    "websockets>=15.0.1",
]
